import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, AlertTriangle, Scale, Ban, CheckCircle2 } from 'lucide-react';

const Section = ({ icon: Icon, iconColor, title, children }) => (
  <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 md:p-8 shadow-xl">
    <div className="flex items-center gap-3 mb-4">
      <div className={`p-2 rounded-xl bg-white/5 ${iconColor}`}>
        <Icon className="w-5 h-5" />
      </div>
      <h2 className="text-lg md:text-xl font-bold text-white">{title}</h2>
    </div>
    <div className="text-slate-300 text-sm md:text-base leading-relaxed space-y-2">
      {children}
    </div>
  </div>
);

const Terms = () => {
  return (
    <div className="flex-grow bg-transparent text-white py-16 px-4 relative z-10">
      {/* Background glows */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden -z-10">
        <div className="absolute top-1/3 left-1/4 w-[20rem] h-[20rem] bg-indigo-500/20 rounded-full blur-[80px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-[20rem] h-[20rem] bg-purple-500/20 rounded-full blur-[80px]"></div>
      </div>

      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm font-semibold px-4 py-2 rounded-full mb-6">
            <Scale className="w-4 h-4" />
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-4">
            Terms &amp; <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-purple-400">Conditions</span>
          </h1>
          <p className="text-slate-400 text-lg max-w-2xl mx-auto">
            Please read these terms carefully before using PhishGuard AI. By using this service, you agree to the conditions described below.
          </p>
          <p className="text-slate-500 text-sm mt-3">Last updated: April 2026</p>
        </div>

        {/* Sections */}
        <div className="space-y-6">
          <Section icon={ShieldCheck} iconColor="text-indigo-400" title="Educational & Informational Purpose">
            <p>
              PhishGuard AI is provided strictly for <strong className="text-white">educational and informational purposes</strong>. It is designed to help users understand potential phishing risks associated with URLs and messages using AI-based analysis.
            </p>
            <p>
              This tool is not intended to serve as a definitive cybersecurity solution or a replacement for professional security software.
            </p>
          </Section>

          <Section icon={AlertTriangle} iconColor="text-yellow-400" title="Accuracy Disclaimer">
            <p>
              Results generated by PhishGuard AI are <strong className="text-white">AI-based predictions</strong> and may not be 100% accurate. Machine learning models can produce false positives (flagging safe content) or false negatives (missing threats).
            </p>
            <p>
              Users should <strong className="text-white">not rely solely</strong> on this tool for making critical security decisions. Always verify results with additional security measures.
            </p>
          </Section>

          <Section icon={Ban} iconColor="text-red-400" title="Limitation of Liability">
            <p>
              PhishGuard AI and its creators accept <strong className="text-white">no liability</strong> for any financial loss, data breach, identity theft, or any other damages arising from reliance on this tool's analysis results.
            </p>
            <p>
              Use of this service is entirely at your own risk. We strongly recommend consulting qualified cybersecurity professionals for critical decisions.
            </p>
          </Section>

          <Section icon={CheckCircle2} iconColor="text-green-400" title="Acceptance of Terms">
            <p>
              By accessing and using PhishGuard AI, you acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2 text-slate-300">
              <li>You understand the tool's educational and informational nature.</li>
              <li>You will not hold the creators liable for any adverse outcomes.</li>
              <li>You will use this service in compliance with applicable laws.</li>
              <li>You will not attempt to abuse, scrape, or exploit the system.</li>
              <li>These terms may be updated at any time without prior notice.</li>
            </ul>
          </Section>
        </div>

        {/* Footer nav */}
        <div className="mt-12 text-center text-sm text-slate-500">
          Also read our{' '}
          <Link to="/privacy" className="text-indigo-400 hover:text-indigo-300 underline underline-offset-4 transition-colors">
            Privacy Policy
          </Link>
          {' '}| Questions? Contact{' '}
          <a href="mailto:shuban1227@gmail.com" className="text-indigo-400 hover:text-indigo-300 underline underline-offset-4 transition-colors">
            shuban1227@gmail.com
          </a>
        </div>
      </div>
    </div>
  );
};

export default Terms;
